rustacean-station/rustacean-station.org

_episodes/000-rust-1.36.0.md
Here's what I've got for show notes, let me know if you think there's anything that ought to be added.
=> Episode 1 show notes

_episodes/001-ruma.md
Still need the filename and the publishing date to be filled in.
=> Episode 2 Draft

_episodes/002-colorado-gold-rust.md
Notes should be reviewed and date should be edited to reflect actual publish date.
=> Episode 2 Show Notes

000-template.md
Just a change to the wording to the call to action, plus removing the quotes from the example datetime because I can never remember if the value is supposed to be a string or bare.
=> Template tweaks

_episodes/014-rust-1.42-1.43.md
I made this episode 14, so the next rustfest interviews will have to become episode 15.
=> Show notes for ep014 on Rust 1.42 + 1.43

_transcripts/012-pietro-pascal-santiago.md
There are about the usual number of (unintelligible) words in here that
could be fixed later on.
=> add transcript for episode 012

_episodes/015-twir-339.md
=> adds reddit link for ep 015

_episodes/010-rust-1.40.0.md, _transcripts/010-rust-1.40.0.md
This transcript is cleaner than average.  No (unintelligible)
placeholders at all!
=> add episode 010 transcript

_transcripts/007-zola.md
Copied, with minor formatting changes and cleanup, from
https://github.com/jeremyjung/softwaresessions
Thanks @jeremyjung for doing 99% of the work.
=> add episode 007 transcript

_transcripts/004-rust-in-production-armin-ronacher.md
The bulk of this is exactly as downloaded from
https://github.com/jeremyjung/softwaresessions
with formatting changes and a lot of corrections.
Corrections were also submitted upstream.
=> add episode 004 transcript

_transcripts/009-jan-lucio.md
Some of the formatting is a little tricky in this second interview.  I
think that most of the time, they're talking about projects (i.e. Tonic,
Tower) but I have used `tonic` and `tower` when we're talking about the
crates.
It's quite ambiguous, but I'm trying to not have sentences where every
third word is in `code` backticks.
=> add episode 009 transcript

_episodes/015-twir-339.md, _episodes/017-twir-341-342.md, _transcripts/017-twir-341-342.md
=> adds in episode page and transcript for ep 017

_episodes/018-twir-343.md
=> Fixes small link typo

_episodes/020-twir-345.md, _transcripts/020-twir-345.md
=> adds initial episode page and transcript for ep 020 covering twir 345

_episodes/020-mun.md
Show notes for episode on Mun.
Didn't have time to write the timestamps - will add later assuming the weekend is kind to me...
=> add episode 020-mun.md

_episodes/021-twir-346.md, _transcripts/021-twir-346.md
=> adds in episode and transcript for twir 346

_transcripts/011-jake-yoshua-stjepan.md
This was a difficult transcript; it has a larger than average number of
"unintelligible" placeholders.  Hopefully someone will correct those in
the future.
=> add episode 011 transcript

_episodes/022-twir-347.md, _transcripts/022-twir-347.md
=> adds episode and description for 022

_episodes/023-twir-348.md, _transcripts/023-twir-348.md
=> adds episode and transcript for 023

_episodes/024-twir-349.md, _transcripts/024-twir-349.md
=> adds in episode page and transcript for ep 24

_episodes/024-katharina-florian.md, _episodes/025-katharina-florian.md
The Florian interview was a bit freeform so timestamps for discrete topics didn't really make sense.
=> Ep25: RustFest w/ Katharina & Florian

_episodes/026-twir-350.md, _transcripts/026-twir-350.md
Adds episode description and partial transcript for TWiR 350.
I've completed the transcript except for the three interviews at the very end. I'm pretty swamped for at least the rest of this week - does anyone by any chance have time to do those?
=> Add twir 350

_transcripts/026-twir-350.md
Add transcriptions for the three interviews in TWIR 350.
I also added a Table of Contents so the individual interviews are linked from the top.  These are short interviews so I'm on the fence whether this is really needed...
=> twir 350: transcribe interviews

000-template.md
Because remembering which values are and are not supposed to be strings
drives me batty.
=> Minor template tweaks

_episodes/030-krustlet.md
Please use https://drive.google.com/file/d/1bIxUfNBjDAj6RfNTx9orFe-S7agLbgkq/view?usp=sharing for audio. Removed a little bit where the guest was clearing their throat.
=> Krustlet Episode

_episodes/030-krustlet.md, _transcripts/030-krustlet.md
An informative and well-recorded episode.  Thanks @jeremyjung and @thomastaylor312!
=> add transcript for episode 030

transcript_style_guide.md, transcript_tools/aws_vocabulary.txt, transcript_tools/transcript_helper.py
A collection of small updates I've been accumulating since May, mostly stuff for transcripts, but also some updates to the style guide, describing the TOC formatting that's already in use in several episodes.
=> Transcript tools updates

_episodes/029-redisjson.md, _transcripts/029-redisjson.md
Great episode!  Thanks to those involved.
There are 3 places I've marked "unintelligible" because I couldn't work out what was being said.
=> Episode 029 transcript

_transcripts/028-rust-1.44-1.45.md
Note, there are duplicate episode numbers.
=> add transcript for episode 028 (Rust 1.44+1.45)

_episodes/031-rust-1.46-1.47.md
I'll update the timestamp just before merging.
=> Rust 1.46 and 1.47

_episodes/032-rust-1.48-1.49.md
Don't have tjtelan's info yet so I'll fix that up along with the timestamp after everything else gets approved.
=> 1.48-1.49 ep

_transcripts/032-rust-1.48-1.49.md
A well-done episode. The audio was especially good this time around.
=> add transcript for episode 032

_episodes/033-rust-1.50-1.51.md, _transcripts/033-rust-1.50-1.51.md
Good episode and nice audio quality. I think I got a pretty clean transcript, only one *unintelligible* that maybe someone can figure out.
I went out on a limb with a few style choices this time... I'll point those out in review comments if anyone wants to rein me in.
The show notes haven't landed yet, which means this won't actually show up in jekyll until an episode file called `_episodes/033-rust-1.50-1.51.md` arrives.
=> add transcript for episode 033

_episodes/034-rust-1.52-1.53.md, _transcripts/034-rust-1.52-1.53.md
Note: won't pass CI, as the episode page doesn't exist yet.
=> add transcript for episode 034

_episodes/035-daniel-stenberg.md
hi @jonhoo I hope I did this correctly, otherwise please advise. I think maybe the date could be wrong.
As we talked about: can you release this on this coming Friday?
=> created episode page for 35

_episodes/036-luca-palmieri.md
@jonhoo for the coming Friday: Sept 10th
=> Prepare for episode 36

_episodes/036-luca-palmieri.md
It is spelled correctly in the title, but not in the description 😅
=> Fix first name

_transcripts/058-rust-1.58-1.59.md
These transcripts are getting a little easier. Either we're putting out better audio, or the AWS transcribe service got better recently. I actually suspect a little of both.
=> add transcript for episode 058

_episodes/twir/2022-05-30-twir-443.md
Audio file https://drive.google.com/file/d/1ZNfvgDO-sDeobNrbhHJe4AMeKxRKfa88/view?usp=sharing
=> Add episode: TWIR 443

_episodes/twir/2022-06-06-twir-444.md
Audio link https://drive.google.com/file/d/1_EW7a5PAuTie0hNoSINrNiggsoofFcXo/view?usp=sharing
=> Add episode 2022-06-07 re TWIR 444

_episodes/twir/2022-06-16-twir-445.md
Audio available via this [Google Drive link](https://drive.google.com/file/d/17LSQ4iU2ILyCn3B3PUQZAr9VgRmAEQxv/view?usp=sharing)
=> Add episode TWIR 445

_episodes/twir/2022-06-23-twir-446.md
A bit late with this one. Audio available here https://drive.google.com/file/d/1Fr1drE5D6lVjpyIJQ0yD8di7dlk38X6n/view?usp=sharing
=> Add episode TWIR 446

_episodes/interviews/2022-12-02-gray-olson.md
This rebases onto #184 to get working CI.
Closes #183.
=> 2022-12-02: Presser with Gray Olson

_episodes/interviews/2022-01-30-zeeshan-ali.md
D-Bus is the protocol and zbus is the crate. :)
---
[I created this PR a year ago](https://github.com/zeenix/rustacean-station.org/pull/1) when this episode came out but turns out I had accidentally created it against my own fork. :facepalm: Anyway, better late than never, right? :)
=> Minor correction to transcript of my zbus session

_episodes/interviews/2023-10-19-rob-ede-kraken.md
just one of my nits around the sort of "branding" of the framework
=> actix-web => Actix Web

_episodes/interviews/2024-04-09-luca-palmieri-pavex.md
=> Fix listing in Pavex interview

_episodes/interviews/2023-08-11-cliff-crosland.md, _episodes/interviews/2024-04-26-orhun-parmaksiz.md, _episodes/twir/2022-06-06-twir-444.md, _episodes/twir/2022-06-16-twir-445.md, _episodes/twir/2022-06-23-twir-446.md
Hi, I appreciate the podcasts. I here fix two listings.
I also noted some broken timestamps in the episodes below but I'm not sure why!
- https://rustacean-station.org/episode/twir-444/
- https://rustacean-station.org/episode/twir-445/
- https://rustacean-station.org/episode/twir-446/
=> Fix listing in two interviews

.github/workflows/jekyll.yml, _episodes/interviews/2024-04-26-orhun-parmaksiz.md
Should significantly reduce CI time for the "episode" check.
=> Only do mp3 check on changed episodes
