.github/workflows/jekyll.yml
000-template.md
_episodes/001-ruma.md
_episodes/002-colorado-gold-rust.md
_episodes/003-rust-1.37.0.md
_episodes/004-rust-in-production-armin-ronacher.md
_episodes/005-rust-1.38.0.md
_episodes/006-rust-1.39.0.md
_episodes/007-zola.md

The following checks are added:
- That the page builds
- That the audio file is available and of the right size
- That the dates are all valid RFC 3339 (~= ISO 8601, but stricter)
- That the generated podcast.rss is a valid RSS feed
The meta for e006 is updated to have the correct file size, and all dates have been updated to match the stricter RFC 3339 format.

Add CI tests for common episode meta errors

---

_episodes/012-pietro-pascal-santiago.md

Hi,
In the episode our [Brazilian group](https://t.me/rustlangbr) is mentioned but there is no reference, name or link for the listener who may want to join the group.
I suggest to add a link :)

Suggestion: Add link to rustlangbr telegram group

---

_transcripts/009-jan-lucio.md
_transcripts/012-pietro-pascal-santiago.md
style.css

To make it easier to jump to the second or third interview in a multi-part episode, add an auto-generated table of contents to a few episodes.
Includes CSS changes to give the TOC and headers a small separation.

Add a table-of-contents to multi-part episode transcripts

---

.github/workflows/jekyll.yml
_episodes/018-twir-343.md
_transcripts/018-twir-343.md

Instead of using the content-length of the 404 page, fail the check with
a helpful error message.

fail gracefully on 404 during mp3 length check

---

_transcripts/008-oli-miri.md

There are 5 places where I couldn't work out what was said (marked with "unintelligible" and a timestamp).
I don't think it hurts the readability much.

add transcript for episode 008

---

_episodes/038-jon-gjengset.md

closes #131 
This PR fixes the spelling error in Jon's Bio.

Fix: Spelling error in Jon Gjengset's episode notes.

---

_episodes/069-twir-441.md

> Tim McNamara and Allen Wyma discuss their highlights from [This Week in Rust 441](https://this-week-in-rust.org/blog/2022/05/04/this-week-in-rust-441/).

New episode TWIR 441

---

_episodes/interviews/2022-05-27-kyle-machulis.md

Seems to have been a copy-paste error from `_episodes/interviews/2022-05-20-rob-ede.md`

_episodes/interviews/2022-05-27-kyle-machulis.md: fix twitter link

---

_layouts/default.html
style.css

So many times I have accidentally clicked in the empty space next to the image and I had to navigate back to the podcast I was listening to.

Remove `display: block` from the header image

---

_episodes/releases/2022-10-05-rust-1.62-1.63-1.64.md

Nothing dramatic, just a timestamp link that's wrong (it stands out because it's out of order).

fix incorrect timestamp in Rust 1.62 release episode

---

_episodes/releases/2022-10-05-rust-1.62-1.63-1.64.md

Certain patterns within links get eaten by some markdown parsers. Usually the offending text are links which contain square brackets and colons, that occur alone in a list item. If you look at [the page for this episode](https://rustacean-station.org/episode/rust-1.62-1.63-1.64/), this text and its link are currently missing.
Work around the bug by introducing a zero-length space character at the beginning of the list item. I verified that this seems to work on some versions of Kramdown (1.2.0 as used by babelmark; 1.10.0 as used by trykramdown.herokuapp.com).
This is my second try ([previous](https://github.com/rustacean-station/rustacean-station.org/pull/176)), and I'm still somewhat unsure whether this will work because I don't know how to test with exactly the same version that might …

work around Kramdown parsing bug

---

.github/workflows/jekyll.yml

Newest Ubuntu (which GitHub CI has now moved to) doesn't even have 2.
This also moves us to https://github.com/w3c/feedvalidator/, which is a fork of rubys original version that, among other things, supports Python 3.

Move to Python 3 maybe?

---

_episodes/interviews/2023-02-04-adam-chalmers.md

I'm 93% sure the correct link should point to https://adamchalmers.com/ :)

Fix a typo in Adam Chalmers's link

---

_episodes/interviews/2023-01-20-shuang-zhu.md

The current link points to 404, and it seems the correct one is https://rustmagazine.org/

Fix a link to rustmagazine

---

_episodes/interviews/2023-01-08-matt-butcher.md

Actually I found it out because I misspelled the name myself in Github search bar... so the typo actually helped me to find what I was looking for.
Ps: I really love the podcast, thanks a lot for the nice content :)

docs: fix typo for Fermyon

---

_episodes/interviews/2023-09-28-ian-ker-sey.md
_episodes/interviews/2023-10-05-dave-macleod.md

These need to be markdown lists, or they don't render correctly.
Also, insert the dash between the timestamp and note, to match the formatting of all the other episodes.
Fixes #231.
cc @allenwyma

fix timestamp formatting in recent interviews

---

_episodes/interviews/2024-03-17-carl-fredrik-samson.md

This PR adds 3 Rust-related podcasts that were mentioned by the guest at the end of the show.

Add show notes to 2024-03-17-carl-fredrik-samson.md

---

.github/workflows/lint.yml

The validator doesn't yet work with Python 3.13+.
https://github.com/w3c/feedvalidator/issues/142

Fix the feed validation

---

.gitignore

.bak created by the spell checker
.swp created by vim

gitignore .bak and .swp files

---

.github/workflows/lint.yml

The w3c validator should now support newer Pyton

Move back to upstream Python
